global using Application = System.Windows.Application;
global using Brush = System.Windows.Media.Brush;
global using Brushes = System.Windows.Media.Brushes;
global using Color = System.Windows.Media.Color;
global using Font = System.Drawing.Font;
global using Point = System.Windows.Point;
global using Size = System.Windows.Size;
global using Rect = System.Windows.Rect;
global using Thickness = System.Windows.Thickness;
global using Visibility = System.Windows.Visibility;
global using Key = System.Windows.Input.Key;
global using MouseButtonEventArgs = System.Windows.Input.MouseButtonEventArgs;
global using KeyEventArgs = System.Windows.Input.KeyEventArgs;
global using MouseEventArgs = System.Windows.Input.MouseEventArgs;
global using DragEventArgs = System.Windows.DragEventArgs;
global using PixelFormats = System.Windows.Media.PixelFormats;
global using BitmapSource = System.Windows.Media.Imaging.BitmapSource;
global using BitmapFrame = System.Windows.Media.Imaging.BitmapFrame;
global using BitmapSizeOptions = System.Windows.Media.Imaging.BitmapSizeOptions;
global using BitmapImage = System.Windows.Media.Imaging.BitmapImage;
global using System;
global using System.Collections.Generic;
global using System.Windows;
global using System.Windows.Controls;
global using System.Windows.Input;
global using System.Windows.Media;
global using System.Windows.Media.Imaging;
global using ToolBox.Models;
global using ToolBox.Services;
